class Fibonacci
  # Fibonacci sequence is generated by adding the two previous terms to get
  # the next term in the sequence ie:
  #   1 + 2 = 3, 3 + 2 = 5 ...
  # First lowest set of terms starts at 1 & 2

  # Calculate the sum of all even terms in the fibonacci sequence
  # Input:
  # Output: Integer

  def self.even_sum_of_terms_under_4million
    previous_term = 1
    next_term = 2
    even_fibonacci_sum = next_term

    current_term = 0

    while current_term < 4000000
      current_term = next_term + previous_term
      even_fibonacci_sum += current_term if current_term.even?

      previous_term = next_term
      next_term = current_term
    end

    return even_fibonacci_sum
  end
end
